[package]
name = "unplug-test"
version = "0.1.0"
authors = ["Derpky"]
edition = "2018"

[dependencies]
anyhow = "1.0"
log = { version = "0.4", features = ["release_max_level_debug"] }
simplelog = "0.8"
tempfile = "3.1.0"
unplug = { path = "../unplug" }

[dev-dependencies]
serial_test = "*"